version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: cardapio_app
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    restart: on-failure

volumes:
  mongodb_data: